services:
  - type: web
    name: hostel-management
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JPA_DDL_AUTO
        value: update
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_INITIAL_ID
        sync: false
      - key: ADMIN_INITIAL_PASSWORD
        sync: false
