spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.forward-headers-strategy=framework
